project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('workshop_data/', include('workshop_data.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import BaseRegisterView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),

]

workshop_data/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from workshop_data.services.general_services import (
    stage_in_work_ready,
    resolution_statement_about_job_over_detail, record_job_order_yes_ready, record_job_order_at_master)
from workshop_data.views.statement_about_job_over_detail_view import (
    AllDetailResolutionOrNotView,
    StatementAboutJobOverDetailView,)
from workshop_data.views import (
    CreateNewBonusView,
    ListAllBonuses,
    ListAllWorkersAndBonuses,
    UpdateBonusView)
from workshop_data.views.services_view import (
    ProductAutocomplete,
    DetailAutocomplete,
    WorkerAutocomplete,
    CategoryDetailAutocomplete,
    BatchlAutocomplete,
    StageForDetaillAutocomplete,
    DetaillForProductAutocomplete,
    WorkerSPUAutocomplete,
    WorkerQRAutocomplete,
)
from workshop_data.views.stage_views import (
    StageManufacturingDetailInWorkInPlanView,
    StageManufacturingDetailInWorkView,
    EditStageManufacturingDetailInWorkView,
    EditStageInDetailView,
    StageInDetailView,
    AddStageInDeatailVeiw,
    EnteringDetailToViewAverageTimeOfWorkView)
from workshop_data.views.complite_view import *
from workshop_data.views.detail_view import (
    DetailAllView,
    DetailCreateView,
    DetailDeleteView,
    AddImageInDetailView,
    DetailImageView,
    DetailAddDetailView,
    DetailEditView,)
from workshop_data.views.product_view import (
    ProductAllView,
    ProductCreateView,
    ProductAddDetailView,
    ProductDataView,
    ProductDeleteView,
    DeleteDetailFromProductView,)
from workshop_data.views.order_views import (
    OrderUserCreateView,
    OrderUserParametrListView,
    OrderUserEditView,
    OrderDeleteView,
    TimeOfWorkInStage,
    AllOrderForAllWorker,
    OrderUserEditMonthView,
)
from workshop_data.views.master_views import (
    # WorkerOrdersListForMaster,
    WorkerListView,
    WorkerAveragePriceListForMaster,
    WorkerSalaryListView)
from workshop_data.views.batch_views import (
    CreateBatchDetailInPlan,
    AllBatchDetailInPlanView,
    # DeleteBatchDetailInPlanView,
    AllBatchDetailProductInPlan)
from workshop_data.views.warehouse_view import (
    WarehouseCreateView,
    WarehouseUpdateView,
    WarehouseListView,
    ViewWarehouseRecord,
    WarehouseCreateSelectedDetailView, WarehouseDeleteView,
)
from workshop_data.views.workshopplan_views import (
    WorkshopPlanUpdateView,
    WorkshopPlanDeleteView,
    WorkshopPlanCreateView,
    WorkshopPlanView,
    WorkshopPlanAddExistingBatchView)
from workshop_data.views.category_detail_views import (
    CreateCategoryDetailView,
    CategoryDetailAllList,
    CategoryDetailUpdateView, CategoryDetailDeleteView,
)
from workshop_data.views.any_view import ShiftTask
from workshop_data.services.general_services import batch_ready, batch_cancel_ready
from workshop_data.views.comment_view import (
    CommentUpdateView,
    WorkshopPlanCommentCreateView,
)
from workshop_data.views.record_job_view import (
    RecordJobCreateView,
    RecordJobEditView,
    AllRecordJobForAllWorker,
    DiagramWorkSPUView,
    ParametersDetailForSPUCreateView,
    ParametersDetailForSPEditeView,
    parameters_detail_for_spu_create_or_edit_redirect,
    RecordJobDeleteView,
    AllRecordJobForWorker,
    AllRecordJobForWorkerPerMonth,
    MillingDetailForSPUCreateView,
    EnteringOperatorWorkTimeView,
    AllOperatorWorkTimeView,
    AverageCoefficientOperators,
    DeletingOperatorWorkTimeView,
    EditOperatorWorkTimeView,
    DiagramWorkTimeOperatorView,
)
from workshop_data.services.evaluation_work_time import get_average_coefficient_all_operator


urlpatterns = [
    path('data_autocomplete_product/', ProductAutocomplete.as_view(), name='data_autocomplete_product'),
    path('data_autocomplete_detail/', DetailAutocomplete.as_view(), name='data_autocomplete_detail'),
    path('data_autocomplete_worker/', WorkerAutocomplete.as_view(), name='data_autocomplete_worker'),
    path('data_autocomplete_worker_spu/', WorkerSPUAutocomplete.as_view(), name='data_autocomplete_worker_cpu'),
    path('data_autocomplete_worker_qr/', WorkerQRAutocomplete.as_view(), name='data_autocomplete_worker_qr'),
    path('data_autocomplete_categorydetail/', CategoryDetailAutocomplete.as_view(), name='data_autocomplete_category_detail'),
    path('data_autocomplete_batch/', BatchlAutocomplete.as_view(), name='data_autocomplete_batch'),
    path('data_autocomplete_satage_in_detail/', StageForDetaillAutocomplete.as_view(), name='data_autocomplete_stage_in_detail'),
    path('data_autocomplete_detail_for_product/', DetaillForProductAutocomplete.as_view(), name='data_autocomplete_detail_for_product'),

    path('<pk>/edit-stage-in-detail/', EditStageInDetailView.as_view(), name='edit_stage_in_detail'),
    path('<pk>/<detail>/all-stage-in-detail/', StageInDetailView.as_view(), name='all_stage_in_detail'),
    path('<pk>/<node>/all-stage-in-node/', StageInDetailView.as_view(), name='all_stage_in_node'),
    path('detail-<detail_id>/add-stage-in-detail/', AddStageInDeatailVeiw.as_view(), name='add_stage_in_detail'),
    path('node-<node_id>/add-stage-in-node/', AddStageInDeatailVeiw.as_view(), name='add_stage_in_node'),
    path('add-stage-in-detail-complete/', add_stage_in_detail_complite, name='add_stage_in_detail_complete'),
    path('new-detail-complete/', detaile_create_complite, name='create_new_detail_complete'),
    path('add-detail-complete/', product_add_detail_complite, name='product_add_detail_complete'),
    path('<detail>/add-detail-in-detail/', DetailAddDetailView.as_view(), name='detail_add_detail'),

    path('new-detail/', DetailCreateView.as_view(), name='create_new_detail'),
    path('edit-detail/<name>/', DetailEditView.as_view(), name='edit_detail'),
    path('detail/all/', DetailAllView.as_view(), name='detail_list_all'),
    path('detail-delete/<id>/', DetailDeleteView.as_view(), name='detail_delete'),
    path('add-image-in-<detail>/', AddImageInDetailView.as_view(), name='add_image_in_detail'),
    path('image-<pk>/', DetailImageView.as_view(), name='image_detail'),

    path('<product>/add-detail/', ProductAddDetailView.as_view(), name='product_add_detail'),
    path('<str:slug>/detail/', ProductDataView.as_view(), name='product_detail_data'),
    path('<product>/delete-<detail>/',DeleteDetailFromProductView.as_view(), name='delete_detail_from_product'),
    path('product/all/', ProductAllView.as_view(), name='product_list_all'),
    path('new-product/', ProductCreateView.as_view(), name='create_new_product'),
    path('new-product-complete/', product_create_complite, name='create_new_product_complete'),
    path('delete-product/<product_name>/', ProductDeleteView.as_view(), name='product_delete'),

    path('create-new-category/', CreateCategoryDetailView.as_view(), name='create_new_category'),
    path('category_detail_all_list/', CategoryDetailAllList.as_view(), name='category_detail_all_list'),
    path('category_detail_update/<id>/', CategoryDetailUpdateView.as_view(), name='category_detail_update'),
    path('category_detail_delete/<id>/', CategoryDetailDeleteView.as_view(), name='category_detail_delete'),
    path('category_detail_list/<str:category>/', DetailAllView.as_view(), name='category_detail_list_all'),

    path('<username>/create_new_order/', OrderUserCreateView.as_view(), name='order_user_create'),
    path('<username>/all_orders/batch-<batch>/operations-<operations>', stage_in_work_ready, name='stage_work_done'),
    path('all_orders/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers'),
    path('master/all_orders/month_<month>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_month'),
    path('master/all_orders/orders-<username>/', AllOrderForAllWorker.as_view(), name='orders-worker-surname-for-master'),
    path('master/all_orders/product_<str:product>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_product'),
    path('master/all_orders/detail_<str:detail_id>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_detail'),
    path('master/all_orders/category_<str:category>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_category'),
    path('<username>/all_orders/', OrderUserParametrListView.as_view(), name='orders_user_list_all'),
    path('<username>/<id>/edit/', OrderUserEditView.as_view(), name='order_user_edit'),
    path('<username>/<id>/delete/', OrderDeleteView.as_view(), name='order_user_delete'),
    path('<username>/month_<str:month>/', OrderUserParametrListView.as_view(), name='orders_user_month_list'),
    path('<username>/statement_about_job_over_detail/', StatementAboutJobOverDetailView.as_view(), name='statement_for_detail'),
    path('<username>/list_all_resolution_or_not_detail/', AllDetailResolutionOrNotView.as_view(), name='list_all_resolution_or_not_detail'),
    path('<username>/resolution_or_not_detail/<id>/done/', resolution_statement_about_job_over_detail, name='resolution_statement_done'),
    path('<username>/order_<id>_edit_month/', OrderUserEditMonthView.as_view(), name='order_user_edit_month'),

    path('master/workers-all-list/', WorkerListView.as_view(), name='workers_list_all'),
    path('master/workers-<position>-list/', WorkerListView.as_view(), name='workers_list_position'),
    path('master/workers-LSM-list/', WorkerListView.as_view(), {'LSM': True},  name='workers_LSM_all'),
    path('master/workers-TRN-list/', WorkerListView.as_view(), {'TRN': True},  name='workers_TRN_all'),
    path('master/workers-MLR-list/', WorkerListView.as_view(), {'MLR': True},  name='workers_MLR_all'),
    path('master/workers-salary-list/', WorkerSalaryListView.as_view(),  name='workers_salary_all'),
    path('master/orders-<username>/', OrderUserParametrListView.as_view(), name='orders-worker-for-master'),

workshop_data/models/record_job.py
from django.db import models
from django.db.models import Avg, Sum, Count, Q, F

from workshop_data.models.month import Month
from sign.models import User

# id операторов участка №2
ID_OPERATORS = [43, 75, 62, 64, 72, 76]
# 61?

class RecordJob(models.Model):
    """Класс описывает запись сделанной работы в БД"""
    date = models.DateField(auto_now_add=True)
    month = models.PositiveSmallIntegerField(
        choices=Month.choices,
        default=Month.NOT_SPECIFIED,
        verbose_name='Месяц')
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name='Рабочий',
        related_name="records_job")
    product = models.ForeignKey(
        'workshop_data.Product',
        on_delete=models.PROTECT,
        verbose_name='Изделие')
    detail = models.ForeignKey(
        'workshop_data.Detail',
        on_delete=models.PROTECT,
        verbose_name='Деталь')
    quantity_1 = models.PositiveSmallIntegerField(
        default=0, blank=True,
        verbose_name='Количество по 1й стороне')
    quantity_2 = models.PositiveSmallIntegerField(
        default=0, blank=True,
        verbose_name='Количество по 2й стороне')
    quantity = models.PositiveSmallIntegerField(
        default=0, blank=True,
         verbose_name='Количество по двум сторонам')
    milling_was = models.BooleanField(default=False, blank=True, null=True)

    order_yes = models.BooleanField(default=False,
                                    verbose_name='Наряд выписан')
    order_at_master = models.BooleanField(default=False,
                                    verbose_name='Наряд сдан')

    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='record_job_spy')
    objects = models.Manager()


    def __str__(self):
        return f'{self.product} {self.detail}'


class Machine(models.TextChoices):
    SMEC_1 = '001', 'Смек 1'
    SMEC_2 = '002', 'Смек 2 барфидер'
    SMEC_3 = '003', 'Смек 3'
    SMEC_4 = '004', 'Смек 4 барфидер'
    SPINNER_1 = '005', 'Шпинер 1'
    SPINNER_2 = '006', 'Шпинер 2'
    HI5000 = '007', 'Малыш'
    NOT_SPECIFIED = '777', 'не указан'


class EvaluationOfTheOperatorsWork(models.Model):
    """Оценка работы оператора"""
    date = models.DateField()
    month = models.PositiveSmallIntegerField(
        choices=Month.choices,
        default=Month.NOT_SPECIFIED,
        verbose_name='Месяц')
    worker = models.ForeignKey(User,
        on_delete=models.PROTECT,
        verbose_name='Рабочий',
        related_name="evaluation_work")
    machine = models.CharField(max_length=3,
                               choices=Machine.choices,
                               default=Machine.NOT_SPECIFIED,
                               verbose_name='Станок')
    barfider = models.BooleanField(default=False)
    work_time = models.SmallIntegerField(default=0)
    green_time = models.SmallIntegerField(default=0)
    product = models.ForeignKey(
        'workshop_data.Product',
        on_delete=models.PROTECT,
        verbose_name='Изделие')
    detail = models.ForeignKey(
        'workshop_data.Detail',
        on_delete=models.PROTECT,
        verbose_name='Деталь')
    quantity_1 = models.PositiveSmallIntegerField(
        default=0, blank=True,
        verbose_name='Количество по 1й стороне')
    quantity_2 = models.PositiveSmallIntegerField(
        default=0, blank=True,
        verbose_name='Количество по 2й стороне')
    quantity = models.PositiveSmallIntegerField(
        default=0, blank=True,
        verbose_name='Количество по двум сторонам')
    milling_was = models.BooleanField(default=False, blank=True, null=True)
    coefficient = models.FloatField()
    coefficient_for_day = models.FloatField(blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='record_job_evaluation')
    objects = models.Manager()

    def get_coefficient(self):
        return self.green_time / self.work_time * (self.work_time / 480)

    def save(self, *args, **kwargs):
        if self.barfider:
            self.coefficient = round((self.get_coefficient()) * 0.3, 2)
        else:
            self.coefficient = round(self.get_coefficient(), 2)
        super(EvaluationOfTheOperatorsWork, self).save(*args, **kwargs)
        self.coefficient_for_day = round(EvaluationOfTheOperatorsWork.objects.filter(
            worker=self.worker.id, date=self.date).aggregate(Sum("coefficient"))['coefficient__sum'], 2)
        q = EvaluationOfTheOperatorsWork.objects.filter(worker=self.worker, date=self.date)
        for record in q:
            record.coefficient_for_day=self.coefficient_for_day
        EvaluationOfTheOperatorsWork.objects.bulk_update(q, ['coefficient_for_day'])
        super(EvaluationOfTheOperatorsWork, self).save(*args, **kwargs)






# class RecordJob2(models.Model):
#     """Класс описывает запись сделанной работы в БД"""
#     class Machine(models.TextChoices):
#         SMEC_1 = '001', 'Смек 1'
#         SMEC_2 = '002', 'Смек 2 барфидер'
#         SMEC_3 = '003', 'Смек 3'
#         SMEC_4 = '004', 'Смек 4 барфидер'
#         SPINNER_1 = '005', 'Шпинер 1'
#         SPINNER_2 = '006', 'Шпинер 2'
#         HI5000 = '007', 'Малыш'
#
#
#     date = models.DateField(auto_now_add=True)
#     month = models.PositiveSmallIntegerField(
#         choices=Month.choices,
#         default=Month.NOT_SPECIFIED,
#         verbose_name='Месяц')
#     user = models.ForeignKey(
#         User,
#         on_delete=models.PROTECT,
#         verbose_name='Рабочий',
#         related_name="records_job")
#     product = models.ForeignKey(
#         'workshop_data.Product',
#         on_delete=models.PROTECT,
#         verbose_name='Изделие')
#     detail = models.ForeignKey(
#         'workshop_data.Detail',
#         on_delete=models.PROTECT,
#         verbose_name='Деталь')
#     quantity_1 = models.PositiveSmallIntegerField(
#         default=0, blank=True,
#         verbose_name='Количество по 1й стороне')
#     quantity_2 = models.PositiveSmallIntegerField(
#         default=0, blank=True,
#         verbose_name='Количество по 2й стороне')
#     quantity = models.PositiveSmallIntegerField(
#         default=0, blank=True,
#          verbose_name='Количество по двум сторонам')
#     milling_was = models.BooleanField(default=False, blank=True, null=True)
#     order_yes = models.BooleanField(default=False,
#                                     verbose_name='Наряд выписан')
#     order_at_master = models.BooleanField(default=False,
#                                     verbose_name='Наряд сдан')
#
#     machine = models.CharField(max_length=3, choices=Machine.choices, verbose_name='Станок')
#     work_time_green = models.FloatField(default=0, null=True, blank=True)
#     barfider = models.BooleanField(default=False)
#     author = models.ForeignKey(User, on_delete=models.PROTECT, related_name='record_job_spy')
#
#     objects = models.Manager()
#
#
#     def __str__(self):
#         return f'{self.product} {self.detail}'

workshop_data/templates/workshop_data/record_job/evaluation_work/all_operator_work_time.html
{% extends 'main.html' %}

{% block title %}
    Коэффициенты всех операторов
{% endblock title %}

{% block content %}
    <table class="table table-success table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
<!--            <th scope="col">Дата</th>-->
            <th scope="col">Станок</th>
            <th scope="col">Оператор</th>
            <th scope="col">Изделие.Деталь</th>
            <th scope="col">Количество</th>
            <th scope="col">Смена/по программе</th>
<!--            <th scope="col">Барфидер</th>-->
            <th scope="col">Коэффициент/Средний</th>
<!--            <th scope="col">Средний коэффициент</th>-->
            <th scope="col"></th>
        </tr>
        </thead>

        <tbody>
            {% for time_record in time_records %}
            {% ifchanged time_record.date %}
                <tr class="table-light">
                    <td></td>
                    <td><h5><strong>{{ time_record.date }}</strong></h5></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                {% endifchanged %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
<!--                        <td></td>-->
                        <td>
                            {{ time_record.get_machine_display }}
                            {% if time_record.barfider %}
                                <abbr title="барфидер" style="text-decoration: none;">(&#10004;)</abbr>
                            {% endif %}
                        </td>
                        <td>{{ time_record.worker.get_full_name }}</td>
                        <td>{{ time_record.product }} <strong>{{ time_record.detail }}</strong></td>
                        <td>{{ time_record.quantity_1 }} / {{ time_record.quantity_2 }} / {{ time_record.quantity }}</td>
                        <td>{{ time_record.work_time }} /
                            <strong>{{ time_record.green_time }}</strong></td>
<!--                        <td>{{ time_record.green_time }}</td>-->
<!--                        <td>-->
<!--                            {% if time_record.barfider %}-->
<!--                                &#10004;-->
<!--                            {% endif %}-->
<!--                            </td>-->
                        <td>
                            {{ time_record.coefficient }} /
                            <strong>{{ time_record.coefficient_for_day }}</strong> /
                        {{ time_record.worker.average_coefficient_operator }}</td>
<!--                        <td>{{ time_record.worker.average_coefficient_operator }}</td>-->
                        <td>
                            <button class="btn btn-outline-primary dropdown-toggle btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Действия
                            </button>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="
                                    {% url 'edit_record_operator_work_time' worker=time_record.worker date=time_record.date id=time_record.id %}">
                                        Исправить
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="
                                    {% url 'delete_record_operator_work_time' worker=time_record.worker date=time_record.date id=time_record.id %}">
                                        Удалить
                                    </a>
                                </li>
                            </ul>
                        </td>

                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endblock content %}

workshop_data/templates/workshop_data/record_job/evaluation_work/average_operators_coefficient.html
{% extends 'main.html' %}
{% load static %}
{% block title %}
    Средние коэффициенты всех операторов
{% endblock title %}

{% block content %}
    <style>
        .wrapper {

        }
        .input-group {
             display:flex;
             flex-wrap: nowrap;
             align-items: center;
             width:220px;
             padding: 10px;
        }
        .form-label {
            padding-right: 10px;
        }
        .btn-coef {
            max-height: 34px;
            margin-top: 10px;

        }
        .head-coef {
            text-align: center;
        }
        .wrapper-table-diagram {
            display:flex;

        }
        .wrapper-table {
            min-width: 668px;
            margin-right: 140px;
        }
        #myChart {

        }
    </style>

<div class="wrapper">
    <form method="POST">
        {% csrf_token %}
        {{ form.media }}
        <div >

            <div class="wrapper-date-input" style="display:flex;justify-content:center;">
                <div class="wrapper-date-input" style="display:flex;justify-content:center;">
                <a href="{% url 'refresh_all_operators_avg_coef' %}" name='refresh' class="btn btn-primary btn-coef">Обновить</a>
            </div>
                <div class='input-group date'>
                    <label class="form-label">{{form.salary.label}}</label>
                    {{ form.salary }}

                    <div class="form-error">{{ form.date2.errors }}</div>
                </div>
                <div class='input-group date'>
                    <label class="form-label">{{form.date1.label}}</label>
                    {{ form.date1 }}

                    <div class="form-error">{{ form.date1.errors }}</div>
                </div>
                <div class='input-group date'>
                    <label class="form-label">{{form.date2.label}}</label>
                    {{ form.date2 }}

                    <div class="form-error">{{ form.date2.errors }}</div>
                </div>
                <input id="button-submit" class="btn btn-primary btn-coef" type="submit" value="Расчет"/></div>
        </div>
    </form>
    <!--

                    <div class="container">-->
    <!--                <h2>Basic Date Time Picker</h2>-->
    <!--                <div class='input-group date' id='picker'>-->
    <!--                    <input type='text' class="form-control"/>-->
    <!--                    <span class="input-group-addon">-->
    <!--                        <span class="glyphicon glyphicon-calendar"></span></span>-->

    <!--                </div>-->
    <!--                <input type="submit" value="Gogogo!"/>-->
    <!--            </div>-->


    <div class="wrapper-table-diagram">
        <div class="wrapper-table">
            <table class="table table-success table-striped">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Оператор</th>
                    <th scope="col">Средний коэффициент</th>
                    <th scope="col">Зарплата</th>
                </tr>
                </thead>
                <tbody>
                {% if avg_range %}
                <h3 class="head-coef">Средний коэффициент за период с <i>{{ date1 }}</i> по <i>{{ date2 }}</i></h3>
                {% for worker, data in avg_range.items %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ worker }}</td>
                    <td>{{ data.0 }}</td>
                    <td>{{ data.1 }}</td>
                    {% endfor %}

                    {% elif operators %}
                    <h3 class="head-coef">Средний коэффициент за все время</h3>
                    {% for worker in operators %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ worker.get_full_name }}</td>
                    <td>{{ worker.average_coefficient_operator }}</td>
                    <td></td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>
            </table>
        </div>


        <div>
            <div style="display: none" id="jsonData" data-json="{{ data }}"></div>

            <canvas id="myChart" width="900px" height="600px">

            </canvas>
        </div>

        <script src="{% static 'js/cdnjs.cloudflare.com_ajax_libs_Chart.js_4.4.0_chart.min.js' %}"></script>
        <script src="{% static 'diagram.js' %}"></script>

         <script>
            const ctx = document.getElementById('myChart').getContext('2d');
    <!--        function loadJson(selector) {-->
    <!--            return JSON.parse(document.querySelector(selector).getAttribute('data-json'));-->
    <!--        }-->
            window.onload = function () {
                ctx.canvas.parentNode.style.height = '500px';
                ctx.canvas.parentNode.style.width = '700px';

                new Chart(ctx, {
                    type: 'bar',
                    data: {
                    labels: [{% for i in data %}'{{ i.name }}',{% endfor %}],
                    datasets: [{
                        label: 'Коэффициент',
                        data: [{% for i in data %}{{ i.coefficient }},{% endfor %}],
                        borderWidth: 1
                    }]
                    },
                    options: {
                        scales: {
                            y: {
                                beginAtZero: true
                            },
                        maintainAspectRatio: false,
                        }
                    }
                });
                };
            </script>
    </div>
</div>

<!--        <script type="text/javascript">-->
<!--         $(function () {-->
<!--             $('#id_date1').datetimepicker({-->
<!--                format: 'DD/MM/YYYY',-->
<!--             });-->
<!--         });-->
<!--         $(function () {-->
<!--            $('#id_date2').datetimepicker({-->
<!--                format: 'DD/MM/YYYY',-->
<!--             });-->
<!--         });-->
<!--      </script>-->



{% endblock content %}

workshop_data/templates/workshop_data/record_job/evaluation_work/delete_record_operator_work_time.html
{% extends 'main.html' %}

{% block title %}
    Удаление записи о работе оператора
{% endblock title %}

{% block content %}
    <h2>Вы действительно хотите удалить Запись</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Подтвердить">
    </form>
{% endblock content %}