project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('workshop_data/', include('workshop_data.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import BaseRegisterView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),

]

workshop_data/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from workshop_data.services.general_services import (
    stage_in_work_ready,
    resolution_statement_about_job_over_detail, record_job_order_yes_ready, record_job_order_at_master)
from workshop_data.views.statement_about_job_over_detail_view import (
    AllDetailResolutionOrNotView,
    StatementAboutJobOverDetailView,)
from workshop_data.views import (
    CreateNewBonusView,
    ListAllBonuses,
    ListAllWorkersAndBonuses,
    UpdateBonusView)
from workshop_data.views.services_view import (
    ProductAutocomplete,
    DetailAutocomplete,
    WorkerAutocomplete,
    CategoryDetailAutocomplete,
    BatchlAutocomplete,
    StageForDetaillAutocomplete,
    DetaillForProductAutocomplete,
    WorkerSPUAutocomplete,
    WorkerQRAutocomplete,
)
from workshop_data.views.stage_views import (
    StageManufacturingDetailInWorkInPlanView,
    StageManufacturingDetailInWorkView,
    EditStageManufacturingDetailInWorkView,
    EditStageInDetailView,
    StageInDetailView,
    AddStageInDeatailVeiw,
    EnteringDetailToViewAverageTimeOfWorkView)
from workshop_data.views.complite_view import *
from workshop_data.views.detail_view import (
    DetailAllView,
    DetailCreateView,
    DetailDeleteView,
    AddImageInDetailView,
    DetailImageView,
    DetailAddDetailView,
    DetailEditView,)
from workshop_data.views.product_view import (
    ProductAllView,
    ProductCreateView,
    ProductAddDetailView,
    ProductDataView,
    ProductDeleteView,
    DeleteDetailFromProductView,)
from workshop_data.views.order_views import (
    OrderUserCreateView,
    OrderUserParametrListView,
    OrderUserEditView,
    OrderDeleteView,
    TimeOfWorkInStage,
    AllOrderForAllWorker,
    OrderUserEditMonthView,
)
from workshop_data.views.master_views import (
    # WorkerOrdersListForMaster,
    WorkerListView,
    WorkerAveragePriceListForMaster,
    WorkerSalaryListView)
from workshop_data.views.batch_views import (
    CreateBatchDetailInPlan,
    AllBatchDetailInPlanView,
    # DeleteBatchDetailInPlanView,
    AllBatchDetailProductInPlan)
from workshop_data.views.warehouse_view import (
    WarehouseCreateView,
    WarehouseUpdateView,
    WarehouseListView,
    ViewWarehouseRecord,
    WarehouseCreateSelectedDetailView, WarehouseDeleteView,
)
from workshop_data.views.workshopplan_views import (
    WorkshopPlanUpdateView,
    WorkshopPlanDeleteView,
    WorkshopPlanCreateView,
    WorkshopPlanView,
    WorkshopPlanAddExistingBatchView)
from workshop_data.views.category_detail_views import (
    CreateCategoryDetailView,
    CategoryDetailAllList,
    CategoryDetailUpdateView, CategoryDetailDeleteView,
)
from workshop_data.views.any_view import ShiftTask
from workshop_data.services.general_services import batch_ready, batch_cancel_ready
from workshop_data.views.comment_view import (
    CommentUpdateView,
    WorkshopPlanCommentCreateView,
)
from workshop_data.views.record_job_view import (
    RecordJobCreateView,
    RecordJobEditView,
    AllRecordJobForAllWorker,
    DiagramWorkSPUView,
    ParametersDetailForSPUCreateView,
    ParametersDetailForSPEditeView,
    parameters_detail_for_spu_create_or_edit_redirect,
    RecordJobDeleteView,
    AllRecordJobForWorker,
    AllRecordJobForWorkerPerMonth,
    MillingDetailForSPUCreateView,
    EnteringOperatorWorkTimeView,
    AllOperatorWorkTimeView,
    AverageCoefficientOperators,
    DeletingOperatorWorkTimeView,
    EditOperatorWorkTimeView,
    DiagramWorkTimeOperatorView,
)
from workshop_data.services.evaluation_work_time import get_average_coefficient_all_operator


urlpatterns = [
    path('data_autocomplete_product/', ProductAutocomplete.as_view(), name='data_autocomplete_product'),
    path('data_autocomplete_detail/', DetailAutocomplete.as_view(), name='data_autocomplete_detail'),
    path('data_autocomplete_worker/', WorkerAutocomplete.as_view(), name='data_autocomplete_worker'),
    path('data_autocomplete_worker_spu/', WorkerSPUAutocomplete.as_view(), name='data_autocomplete_worker_cpu'),
    path('data_autocomplete_worker_qr/', WorkerQRAutocomplete.as_view(), name='data_autocomplete_worker_qr'),
    path('data_autocomplete_categorydetail/', CategoryDetailAutocomplete.as_view(), name='data_autocomplete_category_detail'),
    path('data_autocomplete_batch/', BatchlAutocomplete.as_view(), name='data_autocomplete_batch'),
    path('data_autocomplete_satage_in_detail/', StageForDetaillAutocomplete.as_view(), name='data_autocomplete_stage_in_detail'),
    path('data_autocomplete_detail_for_product/', DetaillForProductAutocomplete.as_view(), name='data_autocomplete_detail_for_product'),

    path('<pk>/edit-stage-in-detail/', EditStageInDetailView.as_view(), name='edit_stage_in_detail'),
    path('<pk>/<detail>/all-stage-in-detail/', StageInDetailView.as_view(), name='all_stage_in_detail'),
    path('<pk>/<node>/all-stage-in-node/', StageInDetailView.as_view(), name='all_stage_in_node'),
    path('detail-<detail_id>/add-stage-in-detail/', AddStageInDeatailVeiw.as_view(), name='add_stage_in_detail'),
    path('node-<node_id>/add-stage-in-node/', AddStageInDeatailVeiw.as_view(), name='add_stage_in_node'),
    path('add-stage-in-detail-complete/', add_stage_in_detail_complite, name='add_stage_in_detail_complete'),
    path('new-detail-complete/', detaile_create_complite, name='create_new_detail_complete'),
    path('add-detail-complete/', product_add_detail_complite, name='product_add_detail_complete'),
    path('<detail>/add-detail-in-detail/', DetailAddDetailView.as_view(), name='detail_add_detail'),

    path('new-detail/', DetailCreateView.as_view(), name='create_new_detail'),
    path('edit-detail/<name>/', DetailEditView.as_view(), name='edit_detail'),
    path('detail/all/', DetailAllView.as_view(), name='detail_list_all'),
    path('detail-delete/<id>/', DetailDeleteView.as_view(), name='detail_delete'),
    path('add-image-in-<detail>/', AddImageInDetailView.as_view(), name='add_image_in_detail'),
    path('image-<pk>/', DetailImageView.as_view(), name='image_detail'),

    path('<product>/add-detail/', ProductAddDetailView.as_view(), name='product_add_detail'),
    path('<str:slug>/detail/', ProductDataView.as_view(), name='product_detail_data'),
    path('<product>/delete-<detail>/',DeleteDetailFromProductView.as_view(), name='delete_detail_from_product'),
    path('product/all/', ProductAllView.as_view(), name='product_list_all'),
    path('new-product/', ProductCreateView.as_view(), name='create_new_product'),
    path('new-product-complete/', product_create_complite, name='create_new_product_complete'),
    path('delete-product/<product_name>/', ProductDeleteView.as_view(), name='product_delete'),

    path('create-new-category/', CreateCategoryDetailView.as_view(), name='create_new_category'),
    path('category_detail_all_list/', CategoryDetailAllList.as_view(), name='category_detail_all_list'),
    path('category_detail_update/<id>/', CategoryDetailUpdateView.as_view(), name='category_detail_update'),
    path('category_detail_delete/<id>/', CategoryDetailDeleteView.as_view(), name='category_detail_delete'),
    path('category_detail_list/<str:category>/', DetailAllView.as_view(), name='category_detail_list_all'),

    path('<username>/create_new_order/', OrderUserCreateView.as_view(), name='order_user_create'),
    path('<username>/all_orders/batch-<batch>/operations-<operations>', stage_in_work_ready, name='stage_work_done'),
    path('all_orders/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers'),
    path('master/all_orders/month_<month>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_month'),
    path('master/all_orders/orders-<username>/', AllOrderForAllWorker.as_view(), name='orders-worker-surname-for-master'),
    path('master/all_orders/product_<str:product>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_product'),
    path('master/all_orders/detail_<str:detail_id>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_detail'),
    path('master/all_orders/category_<str:category>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_category'),
    path('<username>/all_orders/', OrderUserParametrListView.as_view(), name='orders_user_list_all'),
    path('<username>/<id>/edit/', OrderUserEditView.as_view(), name='order_user_edit'),
    path('<username>/<id>/delete/', OrderDeleteView.as_view(), name='order_user_delete'),
    path('<username>/month_<str:month>/', OrderUserParametrListView.as_view(), name='orders_user_month_list'),
    path('<username>/statement_about_job_over_detail/', StatementAboutJobOverDetailView.as_view(), name='statement_for_detail'),
    path('<username>/list_all_resolution_or_not_detail/', AllDetailResolutionOrNotView.as_view(), name='list_all_resolution_or_not_detail'),
    path('<username>/resolution_or_not_detail/<id>/done/', resolution_statement_about_job_over_detail, name='resolution_statement_done'),
    path('<username>/order_<id>_edit_month/', OrderUserEditMonthView.as_view(), name='order_user_edit_month'),

    path('master/workers-all-list/', WorkerListView.as_view(), name='workers_list_all'),
    path('master/workers-<position>-list/', WorkerListView.as_view(), name='workers_list_position'),
    path('master/workers-LSM-list/', WorkerListView.as_view(), {'LSM': True},  name='workers_LSM_all'),
    path('master/workers-TRN-list/', WorkerListView.as_view(), {'TRN': True},  name='workers_TRN_all'),
    path('master/workers-MLR-list/', WorkerListView.as_view(), {'MLR': True},  name='workers_MLR_all'),
    path('master/workers-salary-list/', WorkerSalaryListView.as_view(),  name='workers_salary_all'),
    path('master/orders-<username>/', OrderUserParametrListView.as_view(), name='orders-worker-for-master'),

workshop_data/models/category_detail.py
from django.db import models
from sign.models import User


class CategoryDetail(models.Model):
    """Класс описывает Категорию Детали"""
    name = models.CharField(max_length=50, unique=True, blank=False, verbose_name="Название")
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Автор")

    objects = models.Manager()

    def __str__(self):
        return f'{self.name}'
    

workshop_data/models/product.py
from django.db import models
from django.shortcuts import reverse


class Product(models.Model):
    """Класс описывает Изделие"""
    name = models.CharField(
        max_length=100,
        unique=True,
        blank=False,
        verbose_name='Изделие')
        
    order_number_commercial = models.SmallIntegerField(blank=True, verbose_name='Коммерция')
    order_number_state = models.SmallIntegerField(blank=True, verbose_name='Г/з')
    slug = models.SlugField(max_length=50, blank=True, unique=True)
    detail = models.ManyToManyField(
        "workshop_data.Detail",
        through='workshop_data.ProductDetail',
        related_name="detail_in_product",
        through_fields=('product', 'detail'),)

    objects = models.Manager()

    class Meta:
        verbose_name = 'Изделие'
        verbose_name_plural = 'Изделия'
        ordering = ['name']

    def __str__(self):
        return f'{self.name}'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail_data', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = self.name
        super().save(*args, **kwargs)


class ProductDetail(models.Model):
    """Таблица связи Изделия и Детали"""
    product = models.ForeignKey("workshop_data.Product", on_delete=models.PROTECT)
    detail = models.ForeignKey("workshop_data.Detail", on_delete=models.PROTECT)
    quantity = models.SmallIntegerField(default=1)


class DetailDetail(models.Model):
    """Таблица связи Детали и Детали"""
    main_detail = models.ForeignKey("workshop_data.Detail",
                                    on_delete=models.PROTECT)
    secondary_detail = models.ForeignKey("workshop_data.Detail",
                                         on_delete=models.PROTECT,
                                         related_name="secondary_detail_in_main")
    quantity = models.SmallIntegerField(default=1)

workshop_data/forms/batch.py
from django import forms
from workshop_data.models.workshop_plan import WorkshopPlan
from workshop_data.models.batch_detail_in_plan import BatchDetailInPlan
from workshop_data.models.detail import Detail
from workshop_data.models.comment import Comment


class CreateBatchDetailInPlanForm(forms.ModelForm):
    '''Отображает форму создания новой Партии Деталей'''
    comment = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
    workshopplan_detail = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control"}),
        queryset=WorkshopPlan.objects.all()
    )
    class Meta:
        model = BatchDetailInPlan
        fields = ['workshopplan_detail', 'quantity_in_batch', 'sos', 'comment']

    def __init__(self, *args, **kwargs):
        name = kwargs.pop('object')
        detail = name.split('_')[1]
        detail_id = Detail.objects.get(name=f'{detail}').id
        detail_in_plan = WorkshopPlan.objects.get(detail_id=detail_id)
        super(CreateBatchDetailInPlanForm, self).__init__(*args, **kwargs)
        self.fields['workshopplan_detail'].label = 'Деталь'
        self.fields['workshopplan_detail'].initial = detail_in_plan
        # вот так показывает "LSM", "TRN"...
        # self.fields['stage'].queryset = StageManufacturingDetail.objects.filter(detail_id=detail_id)

        # self.fields['stage'] = forms.ChoiceField(
        #         choices=StageManufacturingDetail.objects.filter(detail_id=detail_id))

        # self.fields['stage'] = forms.ModelChoiceField(
        #     queryset=StageManufacturingDetail.objects.filter(detail_id=detail_id))
        # self.fields['stage'].label = 'Выберите вид работы' #FIXME

    def clean(self):
        comment = self.cleaned_data.pop('comment')
        new_comment = Comment.objects.create(body=comment)
        self.cleaned_data.update({'comment': new_comment})

workshop_data/forms/batch_form.py
from django import forms
from workshop_data.models.workshop_plan import WorkshopPlan
from workshop_data.models.batch_detail_in_plan import BatchDetailInPlan
from workshop_data.models.detail import Detail
from workshop_data.models.comment import Comment, BatchComment


class CreateBatchDetailInPlanForm(forms.ModelForm):
    """Отображает форму создания новой Партии Деталей"""
    comment = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = BatchDetailInPlan
        fields = ['quantity_in_batch', 'sos', 'comment']

    def __init__(self, *args, **kwargs):
        name = kwargs.pop('object')
        self.user = kwargs.pop('user')
        # detail = name.split('_')[1]
        super(CreateBatchDetailInPlanForm, self).__init__(*args, **kwargs)
        # вот так показывает "LSM", "TRN"...
        # self.fields['stage'].queryset = StageManufacturingDetail.objects.filter(detail_id=detail_id)

        # self.fields['stage'] = forms.ChoiceField(
        #         choices=StageManufacturingDetail.objects.filter(detail_id=detail_id))

        # self.fields['stage'] = forms.ModelChoiceField(
        #     queryset=StageManufacturingDetail.objects.filter(detail_id=detail_id))
        # self.fields['stage'].label = 'Выберите вид работы' #FIXME

    def clean(self):
        comment = self.cleaned_data.pop('comment')
        new_comment = BatchComment.objects.create(body=comment, author=self.user)
        self.cleaned_data.update({'comment': new_comment})

workshop_data/forms/bonus_form.py
from dal import autocomplete
from django import forms

from workshop_data.forms.stage_in_work_form import InitialsModelChoiceField
from workshop_data.models import Bonus
from sign.models import User
from workshop_data.models.comment import Comment


class CreateNewBonusForm(forms.ModelForm):
    """Отображает форму создание новой Премии(Bonus) работнику"""
    comment = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Bonus
        fields = ('worker', 'month', 'quantity', 'time', 'comment',)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop("user")
        super(CreateNewBonusForm, self).__init__(*args, **kwargs)
        self.fields['worker'] = InitialsModelChoiceField(
            queryset=User.objects.all(),
            label='Рабочий',
            widget=autocomplete.ModelSelect2(url='data_autocomplete_worker')
        )

    def clean(self):
        comment = self.cleaned_data.pop('comment')
        new_comment = Comment.objects.create(body=comment, author=self.user)
        self.cleaned_data.update({'comment': new_comment})

workshop_data/templates/workshop_data/product/delete_detail_from_product.html
{% extends 'main.html' %}

{% block title %}
    Удаление
{% endblock title %}

{% block content %}
    <h2>Вы действительно хотите удалить Изделие?</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="подтвердить">
    </form>
{% endblock content %}

workshop_data/templates/workshop_data/product/delete_product.html
{% extends 'main.html' %}

{% block title %}
    Удаление
{% endblock title %}

{% block content %}
    <h2>Вы действительно хотите удалить Изделие {{ product.name }}?</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="подтвердить">
    </form>
{% endblock content %}

workshop_data/templates/workshop_data/product/product_add_detail.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    Добавить Деталь в Изделие
{% endblock title %}

{% block content %}
    
    <link rel="stylesheet" href="{% static 'css/product/product_add_detail.css' %}">

    <div class="wrapper-product-add-detail">
        <div class="form">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                {{ form.media }}
                <input type="submit" value="Сохранить" class="btn btn-primary">
                <button type="submit" name="save_and_continue" class="btn btn-primary add">Сохранить и добавить еще</button>
            </form>
        </div>

        <div class="wrapper-table">
            <table class="table table-primary">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Детали</th>
                    <th scope="col"></th>
                </tr>
                </thead>

                {% for detail in product.detail.all %}
                <tbody>
                <tr class="table-light">
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ detail.category }}</td>
                    <td>{{ detail }}</td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
    </div>

   <script>
        $('.add').click(function() {
            $(this).parent().after($('<h3>', {
                'text': 'Деталь добавлена'
            }));
        });
    </script>

{% endblock content %}

workshop_data/templates/workshop_data/product/product_add_detail_complete.html
{% extends 'main.html' %}

{% block title %}
    Добавлено
{% endblock title %}

{% block content %}
    <h3>Деталь добавлена в Изделие</h3>
    <a href="" class="btn btn-primary">Кнопка не работает(нужно передать product)</a>
{% endblock content %}

workshop_data/templates/workshop_data/product/product_add_detail_complite.html
{% extends 'main.html' %}

{% block title %}
    Добавлено
{% endblock title %}

{% block content %}
    <h3>Деталь добавлена в Изделие</h3>
    <a href="" class="btn btn-primary">Кнопка не работает(нужно передать product)</a>
{% endblock content %}

workshop_data/templates/workshop_data/product/product_add_node.html
{% extends 'main.html' %}
{% load static %}

{% block title %}
    Добавить Деталь в Изделие
{% endblock title %}

{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    <link rel="stylesheet" href="{% static 'css/product/product_add_detail.css' %}">
    <h4>Добавить узел в изделие {{ product }}</h4>
    <div class="wrapper-product-add-detail">
        <div class="form">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                {{ form.media }}
                <input type="submit" value="Сохранить" class="btn btn-primary">
                <button type="submit" name="save_and_continue" class="btn btn-primary add">Сохранить и добавить еще</button>
            </form>
        </div>



        <div class="wrapper-table">
            <table class="table table-primary">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Детали</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>
                {% for detail in product.node.all %}
                    {% if detail.node.all %}

                    {% endif %}
                    <tr class="table-light">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>Узел</td>
                        <td>{{ detail }}</td>
                    </tr>
                {% endfor %}

                {% for detail in product.detail.all %}
                <tbody>
                    <tr class="table-light">
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ detail.category }}</td>
                        <td>{{ detail }}</td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>

    </div>

   <script>
        $('.add').click(function() {
            $(this).parent().after($('<h3>', {
                'text': 'Деталь добавлена'
            }));
        });
    </script>

{% endblock content %}

workshop_data/templates/workshop_data/product/product_detail_view.html
{% extends 'main.html' %}
{% load other_tag %}
{% load static %}

{% block title %}
    Детали {{ product }}
{% endblock title %}

{% block content %}
{% total_count 0 %}

    <link rel="stylesheet" href="{% static 'css/detail/product_detail.css' %}">
    <h3>{{ product }}</h3>

    <div class="wrapper-product-detail">
        <div class="wrapper-table-product-detail">
            <table class="table table-success table-striped w-auto">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Название</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col">Категория</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
                </thead>

                {% for detail1 in product.detail.all %}
                    <tr>
                        <th scope="row">{% total_count %}</th>
                        <td>{% if detail1.prefix %} {{ detail1.prefix }}. {% endif %} {{ detail1.get_name_detail }}
                            {% if detail1.productdetail_set.all.first.quantity > 1 %}
                            <strong><i>{{ detail1.productdetail_set.all.first.quantity }}шт.</i></strong>
                            {% endif %}
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                            {% if detail1.category == None %}
                                <td></td>
                            {% else %}
                                <td>{{ detail1.category }}</td>
                            {% endif %}
                        <td><a class="link-image" href="{% url 'image_detail' detail1 %}">Изображение</a></td>
                        {% with detail1 as detail %}
                        <td>
                            {% include 'workshop_data/product/includes/button_dropdown_in_product.html' with detail=detail1 %}
                        </td>
                        {% endwith %}
                    </tr>
                    {% if detail1.secondary_detail.all %}
                        {% for detail2 in detail1.secondary_detail.all %}
                            <tr>
                                <th scope="row">{% total_count %}</th>
                                <td></td>
                                <td>{% if detail2.prefix %} {{ detail2.prefix }}. {% endif %} {{ detail2.get_name_detail }}
                                    {% for i in detail1.detaildetail_set.all %}
                                    {% if i.secondary_detail == detail2 and i.quantity > 1 %}
                                        <strong><i>{{ detail1.detaildetail_set.all.first.quantity }}шт.</i></strong>
                                    {% endif %}

                                    {% endfor %}

                                </td>
                                <td></td>
                                <td></td>
                                <td></td>
                                {% if detail2.category == None %}
                                <td></td>
                                {% else %}
                                <td>{{ detail2.category }}</td>
                                {% endif %}
                                <td><a href="">Изображение</a></td>
                                {% with detail2 as detail %}
                                <td>
                                    {% include 'workshop_data/product/includes/button_dropdown_in_product.html' with detail=detail2 %}
                                </td>
                                {% endwith %}
                            </tr>
                            {% if detail2.secondary_detail.all %}
                                {% for detail3 in detail2.secondary_detail.all %}
                                <tr>
                                    <th scope="row">{% total_count %}</th>
                                    <td></td>
                                    <td></td>
                                    <td>{% if detail3.prefix %} {{ detail3.prefix }}. {% endif %} {{ detail3.get_name_detail }}</td>
                                    <td></td>
                                    <td></td>
                                    {% if detail3.category == None %}
                                    <td></td>
                                    {% else %}
                                    <td>{{ detail3.category }}</td>
                                    {% endif %}
                                    <td><a href="">Изображение</a></td>
                                    {% with detail3 as detail %}
                                    <td>
                                        {% include 'workshop_data/product/includes/button_dropdown_in_product.html' with detail=detail3 %}
                                    </td>
                                    {% endwith %}
                                </tr>
                                    {% for detail4 in detail3.secondary_detail.all %}
                                    <tr>
                                        <th scope="row">{% total_count %}</th>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td>{% if detail4.prefix %} {{ detail4.prefix }}. {% endif %} {{ detail4.get_name_detail }}</td>
                                        <td></td>
                                        {% if detail4.category == None %}
                                        <td></td>
                                        {% else %}
                                        <td>{{ detail4.category }}</td>
                                        {% endif %}
                                        <td><a href="">Изображение</a></td>
                                        {% with detail4 as detail %}
                                        <td>
                                            {% include 'workshop_data/product/includes/button_dropdown_in_product.html' with detail=detail4 %}
                                        </td>
                                        {% endwith %}
                                    </tr>
                {% endfor %}
                {% endfor %}
                {% endif %}
                {% endfor %}
                {% endif %}
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="image-detail">

    </div>
    {% if request.user.position == 'MSR' or  request.user.position == 'EPB'%}
    <div class="master-all-workers-data">
        <div id="master-worker-price-cost-buttons">
            <a class="btn  btn-outline-success btn-sm" type="button"
               href="{% url 'product_add_detail' product=product.name %}">
                Добвить деталь
            </a>
        </div>
    </div>
    {% endif %}

{% endblock content %}