project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('__debug__/', include('debug_toolbar.urls')),
    path('admin/', admin.site.urls),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('workshop_data/', include('workshop_data.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from .views import BaseRegisterView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),

]

workshop_data/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from workshop_data.services.general_services import (
    stage_in_work_ready,
    resolution_statement_about_job_over_detail, record_job_order_yes_ready, record_job_order_at_master)
from workshop_data.views.statement_about_job_over_detail_view import (
    AllDetailResolutionOrNotView,
    StatementAboutJobOverDetailView,)
from workshop_data.views import (
    CreateNewBonusView,
    ListAllBonuses,
    ListAllWorkersAndBonuses,
    UpdateBonusView)
from workshop_data.views.services_view import (
    ProductAutocomplete,
    DetailAutocomplete,
    WorkerAutocomplete,
    CategoryDetailAutocomplete,
    BatchlAutocomplete,
    StageForDetaillAutocomplete,
    DetaillForProductAutocomplete,
    WorkerSPUAutocomplete,
    WorkerQRAutocomplete,
)
from workshop_data.views.stage_views import (
    StageManufacturingDetailInWorkInPlanView,
    StageManufacturingDetailInWorkView,
    EditStageManufacturingDetailInWorkView,
    EditStageInDetailView,
    StageInDetailView,
    AddStageInDeatailVeiw,
    EnteringDetailToViewAverageTimeOfWorkView)
from workshop_data.views.complite_view import *
from workshop_data.views.detail_view import (
    DetailAllView,
    DetailCreateView,
    DetailDeleteView,
    AddImageInDetailView,
    DetailImageView,
    DetailAddDetailView,
    DetailEditView,)
from workshop_data.views.product_view import (
    ProductAllView,
    ProductCreateView,
    ProductAddDetailView,
    ProductDataView,
    ProductDeleteView,
    DeleteDetailFromProductView,)
from workshop_data.views.order_views import (
    OrderUserCreateView,
    OrderUserParametrListView,
    OrderUserEditView,
    OrderDeleteView,
    TimeOfWorkInStage,
    AllOrderForAllWorker,
    OrderUserEditMonthView,
)
from workshop_data.views.master_views import (
    # WorkerOrdersListForMaster,
    WorkerListView,
    WorkerAveragePriceListForMaster,
    WorkerSalaryListView)
from workshop_data.views.batch_views import (
    CreateBatchDetailInPlan,
    AllBatchDetailInPlanView,
    # DeleteBatchDetailInPlanView,
    AllBatchDetailProductInPlan)
from workshop_data.views.warehouse_view import (
    WarehouseCreateView,
    WarehouseUpdateView,
    WarehouseListView,
    ViewWarehouseRecord,
    WarehouseCreateSelectedDetailView, WarehouseDeleteView,
)
from workshop_data.views.workshopplan_views import (
    WorkshopPlanUpdateView,
    WorkshopPlanDeleteView,
    WorkshopPlanCreateView,
    WorkshopPlanView,
    WorkshopPlanAddExistingBatchView)
from workshop_data.views.category_detail_views import (
    CreateCategoryDetailView,
    CategoryDetailAllList,
    CategoryDetailUpdateView, CategoryDetailDeleteView,
)
from workshop_data.views.any_view import ShiftTask
from workshop_data.services.general_services import batch_ready, batch_cancel_ready
from workshop_data.views.comment_view import (
    CommentUpdateView,
    WorkshopPlanCommentCreateView,
)
from workshop_data.views.record_job_view import (
    RecordJobCreateView,
    RecordJobEditView,
    AllRecordJobForAllWorker,
    DiagramWorkSPUView,
    ParametersDetailForSPUCreateView,
    ParametersDetailForSPEditeView,
    parameters_detail_for_spu_create_or_edit_redirect,
    RecordJobDeleteView,
    AllRecordJobForWorker,
    AllRecordJobForWorkerPerMonth,
    MillingDetailForSPUCreateView,
    EnteringOperatorWorkTimeView,
    AllOperatorWorkTimeView,
    AverageCoefficientOperators,
    DeletingOperatorWorkTimeView,
    EditOperatorWorkTimeView,
    DiagramWorkTimeOperatorView,
)
from workshop_data.services.evaluation_work_time import get_average_coefficient_all_operator


urlpatterns = [
    path('data_autocomplete_product/', ProductAutocomplete.as_view(), name='data_autocomplete_product'),
    path('data_autocomplete_detail/', DetailAutocomplete.as_view(), name='data_autocomplete_detail'),
    path('data_autocomplete_worker/', WorkerAutocomplete.as_view(), name='data_autocomplete_worker'),
    path('data_autocomplete_worker_spu/', WorkerSPUAutocomplete.as_view(), name='data_autocomplete_worker_cpu'),
    path('data_autocomplete_worker_qr/', WorkerQRAutocomplete.as_view(), name='data_autocomplete_worker_qr'),
    path('data_autocomplete_categorydetail/', CategoryDetailAutocomplete.as_view(), name='data_autocomplete_category_detail'),
    path('data_autocomplete_batch/', BatchlAutocomplete.as_view(), name='data_autocomplete_batch'),
    path('data_autocomplete_satage_in_detail/', StageForDetaillAutocomplete.as_view(), name='data_autocomplete_stage_in_detail'),
    path('data_autocomplete_detail_for_product/', DetaillForProductAutocomplete.as_view(), name='data_autocomplete_detail_for_product'),

    path('<pk>/edit-stage-in-detail/', EditStageInDetailView.as_view(), name='edit_stage_in_detail'),
    path('<pk>/<detail>/all-stage-in-detail/', StageInDetailView.as_view(), name='all_stage_in_detail'),
    path('<pk>/<node>/all-stage-in-node/', StageInDetailView.as_view(), name='all_stage_in_node'),
    path('detail-<detail_id>/add-stage-in-detail/', AddStageInDeatailVeiw.as_view(), name='add_stage_in_detail'),
    path('node-<node_id>/add-stage-in-node/', AddStageInDeatailVeiw.as_view(), name='add_stage_in_node'),
    path('add-stage-in-detail-complete/', add_stage_in_detail_complite, name='add_stage_in_detail_complete'),
    path('new-detail-complete/', detaile_create_complite, name='create_new_detail_complete'),
    path('add-detail-complete/', product_add_detail_complite, name='product_add_detail_complete'),
    path('<detail>/add-detail-in-detail/', DetailAddDetailView.as_view(), name='detail_add_detail'),

    path('new-detail/', DetailCreateView.as_view(), name='create_new_detail'),
    path('edit-detail/<name>/', DetailEditView.as_view(), name='edit_detail'),
    path('detail/all/', DetailAllView.as_view(), name='detail_list_all'),
    path('detail-delete/<id>/', DetailDeleteView.as_view(), name='detail_delete'),
    path('add-image-in-<detail>/', AddImageInDetailView.as_view(), name='add_image_in_detail'),
    path('image-<pk>/', DetailImageView.as_view(), name='image_detail'),

    path('<product>/add-detail/', ProductAddDetailView.as_view(), name='product_add_detail'),
    path('<str:slug>/detail/', ProductDataView.as_view(), name='product_detail_data'),
    path('<product>/delete-<detail>/',DeleteDetailFromProductView.as_view(), name='delete_detail_from_product'),
    path('product/all/', ProductAllView.as_view(), name='product_list_all'),
    path('new-product/', ProductCreateView.as_view(), name='create_new_product'),
    path('new-product-complete/', product_create_complite, name='create_new_product_complete'),
    path('delete-product/<product_name>/', ProductDeleteView.as_view(), name='product_delete'),

    path('create-new-category/', CreateCategoryDetailView.as_view(), name='create_new_category'),
    path('category_detail_all_list/', CategoryDetailAllList.as_view(), name='category_detail_all_list'),
    path('category_detail_update/<id>/', CategoryDetailUpdateView.as_view(), name='category_detail_update'),
    path('category_detail_delete/<id>/', CategoryDetailDeleteView.as_view(), name='category_detail_delete'),
    path('category_detail_list/<str:category>/', DetailAllView.as_view(), name='category_detail_list_all'),

    path('<username>/create_new_order/', OrderUserCreateView.as_view(), name='order_user_create'),
    path('<username>/all_orders/batch-<batch>/operations-<operations>', stage_in_work_ready, name='stage_work_done'),
    path('all_orders/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers'),
    path('master/all_orders/month_<month>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_month'),
    path('master/all_orders/orders-<username>/', AllOrderForAllWorker.as_view(), name='orders-worker-surname-for-master'),
    path('master/all_orders/product_<str:product>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_product'),
    path('master/all_orders/detail_<str:detail_id>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_detail'),
    path('master/all_orders/category_<str:category>/', AllOrderForAllWorker.as_view(), name='all_orders_list_for_all_workers_category'),
    path('<username>/all_orders/', OrderUserParametrListView.as_view(), name='orders_user_list_all'),
    path('<username>/<id>/edit/', OrderUserEditView.as_view(), name='order_user_edit'),
    path('<username>/<id>/delete/', OrderDeleteView.as_view(), name='order_user_delete'),
    path('<username>/month_<str:month>/', OrderUserParametrListView.as_view(), name='orders_user_month_list'),
    path('<username>/statement_about_job_over_detail/', StatementAboutJobOverDetailView.as_view(), name='statement_for_detail'),
    path('<username>/list_all_resolution_or_not_detail/', AllDetailResolutionOrNotView.as_view(), name='list_all_resolution_or_not_detail'),
    path('<username>/resolution_or_not_detail/<id>/done/', resolution_statement_about_job_over_detail, name='resolution_statement_done'),
    path('<username>/order_<id>_edit_month/', OrderUserEditMonthView.as_view(), name='order_user_edit_month'),

    path('master/workers-all-list/', WorkerListView.as_view(), name='workers_list_all'),
    path('master/workers-<position>-list/', WorkerListView.as_view(), name='workers_list_position'),
    path('master/workers-LSM-list/', WorkerListView.as_view(), {'LSM': True},  name='workers_LSM_all'),
    path('master/workers-TRN-list/', WorkerListView.as_view(), {'TRN': True},  name='workers_TRN_all'),
    path('master/workers-MLR-list/', WorkerListView.as_view(), {'MLR': True},  name='workers_MLR_all'),
    path('master/workers-salary-list/', WorkerSalaryListView.as_view(),  name='workers_salary_all'),
    path('master/orders-<username>/', OrderUserParametrListView.as_view(), name='orders-worker-for-master'),

workshop_data/models/bonus.py
from django.db import models
from sign.models import User
from workshop_data.models import Month
from workshop_data.models.comment import Comment

class Bonus(models.Model):
    """Класс описывает модель Премии(Bonus) выписываемой работнику мастером или начальником"""
    worker = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        blank=False,
        verbose_name="Работник",
        related_name="user_bonus")
    quantity = models.SmallIntegerField(default=0, verbose_name="Сумма")
    month = models.PositiveSmallIntegerField(
        choices=Month.choices,
        default=Month.NOT_SPECIFIED,
        verbose_name='Месяц')
    time = models.SmallIntegerField(default=0, verbose_name="Затраченное время")
    # comment = models.ForeignKey(
    #     Comment,
    #     on_delete=models.PROTECT,
    #     blank=False,
    #     verbose_name="Комментарий")
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        blank=False,
        verbose_name="Автор",
        related_name="author_bonus")

    objects = models.Manager()

    def __str__(self):
        return f'Премия {self.pk}'

workshop_data/models/category_detail.py
from django.db import models
from sign.models import User


class CategoryDetail(models.Model):
    """Класс описывает Категорию Детали"""
    name = models.CharField(max_length=50, unique=True, blank=False, verbose_name="Название")
    author = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="Автор")

    objects = models.Manager()

    def __str__(self):
        return f'{self.name}'
    

workshop_data/models/warehouse.py
from django.db import models

from sign.forms import User


class Unit(models.IntegerChoices):
    UNITS = 1, "шт."
    KILOGRAM = 2, "кг."
    NOT_SPECIFIED = 3, "не указан"


class Warehouse(models.Model):
    """Класс описывает детали/заготовки на складе"""
    date = models.DateTimeField(auto_now_add=True)
    section = models.SmallIntegerField(default=423,
                                       verbose_name="Участок")
    detail = models.ForeignKey("workshop_data.Detail",
                               on_delete=models.DO_NOTHING,
                               related_name="in_warehouse_detail")
    product = models.ForeignKey("workshop_data.Product",
                                on_delete=models.DO_NOTHING,
                                related_name="in_warehouse_product")
    expenditures = models.PositiveSmallIntegerField(default=0, verbose_name="Расход")
    income = models.PositiveSmallIntegerField(default=0, verbose_name="Приход")
    semis = models.BooleanField(verbose_name="Заготовка")
    balance_semis_on_this_moment = models.PositiveSmallIntegerField(default=0)
    intermediate_detail = models.BooleanField(verbose_name="Полуфабрикат")
    balance_intermediate_detail_on_this_moment = models.PositiveSmallIntegerField(default=0)
    balance_in_warehouse_on_this_moment = models.PositiveSmallIntegerField(default=0)
    cell = models.SmallIntegerField(default=0)
    employee = models.ForeignKey("sign.User",
                                 on_delete=models.PROTECT,
                                 verbose_name="Сотрудник")
    unit = models.PositiveSmallIntegerField(
        choices=Unit.choices,
        default=Unit.NOT_SPECIFIED,
        verbose_name='Единица измерения')
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name='user_warehouse',
        blank=True, null=True)

    objects = models.Manager()

    # def save(self, *args, **kwargs):
    #     self.balance_in_warehouse_on_this_moment = self.detail.get_balance_on_this_moment() + self.income - self.expenditures ####
    #     if self.semis:
    #         self.balance_semis_on_this_moment += self.detail.balance_semis_in_warehouse + self.income - self.expenditures
    #         self.balance_intermediate_detail_on_this_moment = self.detail.balance_intermediate_detail_in_warehouse
    #         self.detail.balance_semis_in_warehouse += self.income - self.expenditures
    #     elif self.intermediate_detail:
    #         self.balance_intermediate_detail_on_this_moment += self.detail.balance_intermediate_detail_in_warehouse + self.income - self.expenditures
    #         self.balance_semis_on_this_moment = self.detail.balance_semis_in_warehouse
    #         self.detail.balance_intermediate_detail_in_warehouse += self.income - self.expenditures
    #     self.detail.save()
    #     super(Warehouse, self).save(*args, **kwargs)

workshop_data/forms/batch.py
from django import forms
from workshop_data.models.workshop_plan import WorkshopPlan
from workshop_data.models.batch_detail_in_plan import BatchDetailInPlan
from workshop_data.models.detail import Detail
from workshop_data.models.comment import Comment


class CreateBatchDetailInPlanForm(forms.ModelForm):
    '''Отображает форму создания новой Партии Деталей'''
    comment = forms.CharField(widget=forms.Textarea(attrs={"class": "form-control"}))
    workshopplan_detail = forms.ModelChoiceField(
        widget=forms.Select(attrs={"class": "form-control"}),
        queryset=WorkshopPlan.objects.all()
    )
    class Meta:
        model = BatchDetailInPlan
        fields = ['workshopplan_detail', 'quantity_in_batch', 'sos', 'comment']

    def __init__(self, *args, **kwargs):
        name = kwargs.pop('object')
        detail = name.split('_')[1]
        detail_id = Detail.objects.get(name=f'{detail}').id
        detail_in_plan = WorkshopPlan.objects.get(detail_id=detail_id)
        super(CreateBatchDetailInPlanForm, self).__init__(*args, **kwargs)
        self.fields['workshopplan_detail'].label = 'Деталь'
        self.fields['workshopplan_detail'].initial = detail_in_plan
        # вот так показывает "LSM", "TRN"...
        # self.fields['stage'].queryset = StageManufacturingDetail.objects.filter(detail_id=detail_id)

        # self.fields['stage'] = forms.ChoiceField(
        #         choices=StageManufacturingDetail.objects.filter(detail_id=detail_id))

        # self.fields['stage'] = forms.ModelChoiceField(
        #     queryset=StageManufacturingDetail.objects.filter(detail_id=detail_id))
        # self.fields['stage'].label = 'Выберите вид работы' #FIXME

    def clean(self):
        comment = self.cleaned_data.pop('comment')
        new_comment = Comment.objects.create(body=comment)
        self.cleaned_data.update({'comment': new_comment})

workshop_data/templates/workshop_data/plan/add_existing_batch_in_plan.html
{% extends 'main.html' %}

{% block title %}
    Добавление существующей партии
{% endblock title %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        {{ form.media }}
        <input type="submit" value="Отправить" class="btn btn-primary">
    </form>
{% endblock content %}

workshop_data/templates/workshop_data/plan/add_existing_batch_in_plan_complete.html
{% extends 'main.html' %}

{% block title %}
    Добавлено
{% endblock title %}

{% block content %}
    <h3>Существующая партия добавлена в План</h3>
{% endblock content %}

workshop_data/templates/workshop_data/plan/delete_object_from_workshopplan.html
{% extends 'main.html' %}

{% block title %}
    Удаление
{% endblock title %}

{% block content %}
    <h2>Вы действительно хотите удалить Деталь ... из Плана?</h2>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="подтвердить">
    </form>
{% endblock content %}

workshop_data/templates/workshop_data/plan/plan_list_all.html
{% extends 'main.html' %}
{% load static %}
{% load other_tag %}
{% load workshopplan_tag %}

{% block title %}
    План цеха
{% endblock title %}

{% block content %}
{% total_count 0 %}
    <link rel="stylesheet" href="{% static 'css/plan/plan.css' %}" type="text/css">
    <div class="filter-wrapper">
        <form method="GET">
            <div class="filter">
                <h5>Найти по изделию  {{ filter.form.product }}{{ filter.form.media }}</h5>
                <h5>Найти по детали {{ filter.form.detail }}{{ filter.form.media }}!!! не работает фильтр по детали !!!</h5>

            </div>
            <div class="input-group mb-3">
                <div class="input-group-text">
                    <h5 style="margin-right: 10px;">Выбрать месяц</h5>
                    {{ filter.form.month }}
                    {{ filter.form.media }}
                </div>
            </div>
            <input type="submit" value="Найти">
        </form>
    </div>

    <hr>
    <h4>План цеха на {{ month }} </h4>

    <table class="table table-primary table-hover ">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col"></th>
                <th scope="col">Месяц</th>
                <th scope="col" style="width: 140px;">Деталь</th>
                <th scope="col" style="width: 140px;">Входящие</th>
                <th scope="col" style="width: 140px;">Входящие</th>
                <th scope="col" style="width: 140px;">Входящие</th>
                <th scope="col">Всего - Гос/Ком</th>
                <th scope="col" style="width: 93px;">заготовки</th>
                <th scope="col" style="width: 70px;">п/ф</th>
                <th scope="col" style="width: 87px;">ед.изм</th>
                <th scope="col">В работе</th>
                <th scope="col"></th>
            </tr>
        </thead>

        {% for product in products %}
        <tbody>
        {% ifchanged product %}
        <tr class="table-light">
            <td></td>
            <td><h5><strong>{{ product }}</strong></h5></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endifchanged %}
        {% for month in filter.form.month.value %}
            {% for detail1 in product.detail.all %}
                {% object_workshopplan product=product detail=detail1 month=month as object %}

                    <tr class="{% if object.sos == True %}table-danger
                                           {% else %}{% endif %}"
                        style="{% if object %}color:#E32636{% endif %}">
                        <th scope="row">{% total_count %}</th>
                        <td></td>
                        <td>{{ object.get_month_display }}</td>
                        <td>{% if detail1.prefix %} {{ detail1.prefix }}. {% endif %} {{ detail1.get_name_detail }}
                            <a title="Комментарии" data-bs-toggle="modal" data-bs-target="" href="#{{object.id}}">&#9776;</a>
                            {% include 'workshop_data/plan/includes/workshop_plan_modal_window_comments_list.html' %}
                        </td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            {% if object %}
                                {{ object.get_quantity }} -
                                {{ object.quantity_state_order }}гз/
                                {{ object.quantity_commercial_order }}ком
                            {% endif %}
                        </td>
                        <td>{{ detail1.balance_semis_in_warehouse }}заг</td>
                        <td>{{ detail1.balance_intermediate_detail_in_warehouse }}п/ф</td>
                        <td>{{ detail1.in_warehouse.get_unit_display }}</td>
                        <td><a href="{% url 'batchs_in_plan' object %}">в работе</a></td>

                        <td>{% include 'workshop_data/plan/includes/button_dropdown_menu_plan.html' %}</td>
                    </tr>

                    {% if detail1.secondary_detail.all %}
                        {% for detail2 in detail1.secondary_detail.all %}
                        {% object_workshopplan product=product detail=detail2 month=month as object2 %}
                        {% with object=object2 %}
                                <tr class="{% if object.sos == True %}table-danger
                                           {% else %}{% endif %}">
                                <th scope="row">{% total_count %}</th>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>{% if detail2.prefix %} {{ detail2.prefix }}. {% endif %} {{ detail2.get_name_detail }}
                                    <a title="Комментарии" data-bs-toggle="modal" data-bs-target="" href="#{{object.id}}">&#9776;</a>
                                    {% include 'workshop_data/plan/includes/workshop_plan_modal_window_comments_list.html' %}
                                </td>
                                <td></td>
                                <td></td>
                                <td>
                                    {% if object %}
                                        {{ object.get_quantity }} -
                                        {{ object.quantity_state_order }}гз/
                                        {{ object.quantity_commercial_order }}ком
                                    {% endif %}
                                </td>
                                <td>{{ detail2.balance_semis_in_warehouse }}заг</td>
                                <td>{{ detail2.balance_intermediate_detail_in_warehouse }}п/ф</td>
                                <td>{{ detail2.in_warehouse.get_unit_display }}</td>
                                <td></td>
                                <td>{% include 'workshop_data/plan/includes/button_dropdown_menu_plan.html' %}</td>
                            </tr>

                        {% endwith %}
                                {% if detail2.secondary_detail.all %}
                                    {% for detail3 in detail2.secondary_detail.all %}
                                    {% object_workshopplan product=product detail=detail3 month=month as object3 %}
                                    {% with object=object3 %}

                                            <tr class="{% if object.sos == True %}table-danger
                                                       {% else %}{% endif %}">
                                            <th scope="row">{% total_count %}</th>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td></td>
                                            <td>{% if detail3.prefix %} {{ detail3.prefix }}. {% endif %} {{ detail3.get_name_detail }}
                                                <a title="Комментарии" data-bs-toggle="modal" data-bs-target="" href="#{{object.id}}">&#9776;</a>
                                                {% include 'workshop_data/plan/includes/workshop_plan_modal_window_comments_list.html' %}
                                            </td>
                                            <td></td>
                                            <td>
                                                {% if object %}
                                                    {{ object.get_quantity }} -
                                                    {{ object.quantity_state_order }}гз/
                                                    {{ object.quantity_commercial_order }}ком
                                                {% endif %}
                                            </td>
                                            <td>{{ detail3.balance_semis_in_warehouse }}заг</td>
                                            <td>{{ detail3.balance_intermediate_detail_in_warehouse }}п/ф</td>
                                            <td>{{ detail3.in_warehouse.get_unit_display }}</td>
                                            <td></td>
                                            <td>{% include 'workshop_data/plan/includes/button_dropdown_menu_plan.html' %}</td>
                                        </tr>

                                    {% endwith %}
                                            {% if detail3.secondary_detail.all %}
                                                {% for detail4 in detail3.secondary_detail.all %}
                                                {% object_workshopplan product=product detail=detail4 month=month as object4 %}
                                                {% with object=object4 %}
                                                        <tr class="{% if object.sos == True %}table-danger
                                                                   {% else %}{% endif %}">
                                                        <th scope="row">{% total_count %}</th>
                                                        <td></td>
                                                        <td></td>
                                                        <td></td>
                                                        <td></td>
                                                        <td></td>
                                                        <td>{% if detail4.prefix %} {{ detail4.prefix }}. {% endif %} {{ detail4.get_name_detail }}
                                                            <a title="Комментарии" data-bs-toggle="modal" data-bs-target="" href="#{{object.id}}">&#9776;</a>
                                                            {% include 'workshop_data/plan/includes/workshop_plan_modal_window_comments_list.html' %}
                                                        </td>
                                                        <td>
                                                            {% if object %}
                                                                {{ object.get_quantity }} -
                                                                {{ object.quantity_state_order }}гз/
                                                                {{ object.quantity_commercial_order }}ком
                                                            {% endif %}
                                                        </td>
                                                        <td>{{ detail4.balance_semis_in_warehouse }}заг</td>
                                                        <td>{{ detail4.balance_intermediate_detail_in_warehouse }}п/ф</td>
                                                        <td>{{ detail4.in_warehouse.get_unit_display }}</td>
                                                        <td></td>
                                                        <td>{% include 'workshop_data/plan/includes/button_dropdown_menu_plan.html' %}</td>
                                                        </tr>
                                                {% endwith %}
                                                {% endfor %}
                                            {% endif %}
                                    {% endfor %}
                                {% endif %}
                        {% endfor %}
                    {% endif %}

            {% endfor %}
            {% endfor %}
            </tbody>



        {% endfor %}


        {% comment %}
        {% for object in filter.qs %}
        <tbody>
        {% ifchanged object.product %}
        <tr class="table-light">
            <td></td>
            <td><h5>{{ object.product }}</h5></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>

            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endifchanged %}
        <tr class="{% if object.sos == True %}table-danger
                                       {% else %}{% endif %}">
            <th scope="row">{{ forloop.counter }}</th>
            <td></td>
            <td>{{ object.get_month_display }}</td>


            <td>{% if object.detail %}
                <a href="">{{ object.detail }}</a>
                {% endif %}
            </td>
            <td></td>
            <td></td>
            <td></td>
            <td>
                <a href="">{{ object.get_quantity }}</a> -
                <a href="">{{ object.quantity_state_order }}/{{ object.quantity_commercial_order }}</a>
            </td>
            <td><a href="{% url 'batchs_in_plan' object %}">{{ object.get_quantity_for_all_batch }}</a></td>
            <td><a href="">{{ object.sos }}</a></td>
            <td>
                {% include 'workshop_data/plan/includes/button_dropdown_menu_plan.html' %}
            </td>
        </tr>
        </tbody>
        {% endfor %}
        {% endcomment %}
    </table>


{% include 'workshop_data/plan/includes/workshop_plan_modal_window_comments_list.html' %}


{% endblock content %}